<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>${project.groupId}:${project.artifactId}</name>
    <url>https://github.com/jme-admin-ch/jme-security-example/tree/main</url>
    <scm>
        <url>https://github.com/jme-admin-ch/jme-security-example.git</url>
        <connection>scm:git:git://github.com/jme-admin-ch/jme-security-example.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/jme-admin-ch/jme-security-example.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <name>BIT</name>
            <email>jeap-community@bit.admin.ch</email>
            <organization>Federal Office of Information Technology, Systems and Telecommunication FOITT</organization>
            <organizationUrl>https://www.bit.admin.ch/</organizationUrl>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <parent>
        <groupId>ch.admin.bit.jeap</groupId>
        <artifactId>jeap-spring-boot-parent</artifactId>
        <version>37.6.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <artifactId>jme-security-example</artifactId>
    <version>1.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <jeap-oauth-mock-server.version>7.3.0</jeap-oauth-mock-server.version>
        <jme-spring-boot-integration-test.version>5.7.4</jme-spring-boot-integration-test.version>
        <logbook.version>4.0.4</logbook.version>
    </properties>

    <modules>
        <module>jme-security-scs</module>
        <module>jme-security-ui</module>
        <module>jme-security-auth-scs</module>
        <module>jme-security-resource-service</module>
        <module>jme-security-client-service</module>
        <module>jme-security-clientresource-service</module>
        <module>jme-security-test</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Bundle-License>https://www.apache.org/licenses/LICENSE-2.0</Bundle-License>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <!-- Attach an empty javadoc jar to every module because javadoc generation is skipped by the parent. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>empty-javadoc-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>javadoc</classifier>
                            <classesDirectory>${project.basedir}</classesDirectory>
                            <excludes>
                                <exclude>**/**</exclude>
                            </excludes>
                            <forceCreation>true</forceCreation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
