server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          jme-security-client-service:
            client-id: "jme-security-client-service"
            client-secret: "secret"
            authorization-grant-type: "client_credentials"
            provider: "local-mock"
          jme-security-client-service-alternate-roles:
            client-id: "jme-security-client-service-alternate-roles"
            client-secret: "secret"
            authorization-grant-type: "client_credentials"
            provider: "local-mock"
          jme-security-client-service-bpscoped:
            client-id: "jme-security-client-service-bpscoped"
            client-secret: "secret"
            authorization-grant-type: "client_credentials"
            scope: ["openid", "bproles:11111"]
            provider: "local-mock"
          jme-security-client-service-roles-pruned:
            client-id: "jme-security-client-service-roles-pruned"
            client-secret: "secret"
            authorization-grant-type: "client_credentials"
            provider: "local-mock"
          jme-security-client-service-direct-access-user:
            client-id: "jme-security-client-service-direct-access-user"
            client-secret: "direct-access-user-secret"
            authorization-grant-type: "password"
            provider: "local-mock"
        provider:
          local-mock:
            issuer-uri: "http://localhost:8081/jme-security-auth-scs"

jme:
  security:
    client:
      resource-url: "http://localhost:8070/jme-security-resource-service"
      scs-url: "http://localhost:8080/jme-security-scs"
      client-resource-url: "http://localhost:8060/jme-security-clientresource-service"

logging:
  level:
    ch.admin.bit.jeap.jme.security.oauth.client: DEBUG
